logo_path = './resource/safe_road.png'
accident_dataset= './resource/US_Accidents_March23.csv'
ohio_accident_dataset_csv = './resource/Ohio_Accidents_March23.csv'
actual_lat_lng_dataset = './resource/Lat_Lng_Accidents_March23.csv'
hospital_dataset = './resource/us_hospital_locations.csv'
ohio_hospital_dataset_csv = './resource/Ohio_Hospital_March23.csv'
