name: Deploy to Safe Roads on Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends docker.io=19.03.6-0ubuntu1.21.10.1
      continue-on-error: true

    - name: Build Docker image
      run: |
        docker build -t safe-roads:${{ github.sha }} .
        docker tag safe-roads:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/safe-roads:${{ github.sha }}
