name: Deploy to Safe Roads on Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends docker.io=19.03.6-0ubuntu1.21.10.1
      continue-on-error: true

    - name: Build Docker image
      run: |
        docker build -t safe-roads:${{ github.sha }} .
        docker tag safe-roads:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/safe-roads:${{ github.sha }}
      working-directory: safe-roads  # Set the working directory to the base directory

    - name: Configure Docker for Google Container Registry
      run: |
        gcloud auth configure-docker
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        CLOUDSDK_COMPUTE_ZONE: us-central1

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/safe-roads:${{ github.sha }}
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        CLOUDSDK_COMPUTE_ZONE: us-central1

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy safe-roads \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/safe-roads:${{ github.sha }} \
          --platform managed
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        CLOUDSDK_COMPUTE_ZONE: us-central1
